
name: docs

on:
  push:
    tags:
      - 'v*' # only release a versioned tag, such as v.X.Y.Z
    branches: ['*']

jobs:
  build-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          set-safe-directory: $GITHUB_WORKSPACE
      - name: Copy Requirements
        uses: canastro/copy-file-action@master
        with:
          source: "python/requirements.txt"
          target: "docs/requirements.txt"
      - name: Build HTML
        uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "apt-get update -y && apt-get install -y git"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html/
#      - name: Deploy ðŸš€
#        uses: peaceiris/actions-gh-pages@v3
#        if: $${{ github.ref }} == 'refs/heads/master'
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: docs/_build/html
